apiVersion: v1
kind: Pod
metadata:
  name: opa-disallowed-tags
  labels:
    owner: aUserName
spec:
  containers:
    - name: nginx
      image: nginx:latest
      resources:
        limits:
          cpu: "100m"
          memory: "1Gi"
