apiVersion: v1
kind: Pod
metadata:
  name: opa-allowed-tags
  labels:
    owner: aUserName
spec:
  containers:
    - name: nginx
      image: nginx:1.21.6
      resources:
        limits:
          cpu: "100m"
          memory: "1Gi"
